-- create database 
CREATE DATABASE IF NOT EXISTS house_look;
-- create user@localhost
GRANT ALL PRIVILEGES ON house_look.* TO 'user'@'localhost';
FLUSH PRIVILEGES;

-- create places table
USE house_look;
CREATE TABLE IF NOT EXISTS `places`(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(60) NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- create houses table
CREATE TABLE IF NOT EXISTS `houses`(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	place_id INT NOT NULL,
	name VARCHAR(60) NOT NULL,
	vacancy BOOLEAN DEFAULT true,
	latitude FLOAT,
	longitude FLOAT,
	FOREIGN KEY (place_id) REFERENCES places(id)
	  ON UPDATE CASCADE ON DELETE RESTRICT
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- create rooms table
CREATE TABLE IF NOT EXISTS `rooms` (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	house_id INT NOT NULL,
	place_id INT NOT NULL,
	name VARCHAR(60),
	vacancy BOOLEAN DEFAULT true,
	type VARCHAR(60),
	price FLOAT,
	description VARCHAR(128),
	FOREIGN KEY (house_id) REFERENCES houses(id)
	  ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (place_id) REFERENCES places(id)
	  ON UPDATE CASCADE ON DELETE RESTRICT
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- create users table
CREATE TABLE IF NOT EXISTS `users` (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(60) NOT NULL,
	contact VARCHAR(60)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- create Reviews table
CREATE TABLE IF NOT EXISTS `reviews` (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	house_id INT NOT NULL,
	room_id INT NOT NULL,
	user_id INT NOT NULL,
	description VARCHAR(1024),
	FOREIGN KEY (house_id) REFERENCES houses(id)
	  ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (room_id) REFERENCES rooms(id)
	  ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (user_id) REFERENCES users(id)
	  ON UPDATE CASCADE ON DELETE RESTRICT
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- create owners table
CREATE TABLE IF NOT EXISTS `owners` (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(60) NOT NULL,
	house_id INT NOT NULL,
	contact VARCHAR(60),
	FOREIGN KEY (house_id) REFERENCES houses(id)
	  ON UPDATE CASCADE ON DELETE RESTRICT
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;
FLUSH PRIVILEGES;
